---
name: App-CPAN2Pkg
version: 0.4.1
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
abstract: generating native linux packages from cpan
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CPANPLUS::Shell::Default::Plugins::Prereqs: 0
  Class::XSAccessor: 0
  Curses: 0
  Curses::UI: 0
  Curses::UI::POE: 0
  FindBin: 0
  Hook::Output::File: 0
  List::MoreUtils: 0
  POE: 0
  perl: 5.010
build_requires:
  CPANPLUS::Shell::Default::Plugins::Prereqs: 0
  Class::XSAccessor: 0
  Curses: 0
  Curses::UI: 0
  Curses::UI::POE: 0
  FindBin: 0
  Hook::Output::File: 0
  List::MoreUtils: 0
  POE: 0
  Test::More: 0
  perl: 5.010
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  App::CPAN2Pkg:
    file: lib/App/CPAN2Pkg.pm
    version: 0.4.1
  App::CPAN2Pkg::Curses:
    file: lib/App/CPAN2Pkg/Curses.pm
  App::CPAN2Pkg::Module:
    file: lib/App/CPAN2Pkg/Module.pm
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
