---
name: App-CPAN2Pkg
version: 1.1.0
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
abstract: generating native linux packages from cpan
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=App-CPAN2Pkg
  homepage: http://search.cpan.org/dist/App-CPAN2Pkg
  license: http://dev.perl.org/licenses/
  repository: http://repo.or.cz/w/app-cpan2pkg.git
requires:
  CPANPLUS::Shell::Default::Plugins::Prereqs: 0
  Class::XSAccessor: 0
  Curses: 0
  Curses::UI: 0
  Curses::UI::POE: 0
  File::Basename: 0
  FindBin: 0
  Getopt::Euclid: 0
  Hook::Output::File: 0
  List::MoreUtils: 0
  POE: 0
  perl: 5.010
build_requires:
  CPANPLUS::Shell::Default::Plugins::Prereqs: 0
  Class::XSAccessor: 0
  Curses: 0
  Curses::UI: 0
  Curses::UI::POE: 0
  File::Basename: 0
  FindBin: 0
  Getopt::Euclid: 0
  Hook::Output::File: 0
  List::MoreUtils: 0
  POE: 0
  Test::More: 0
  perl: 5.010
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  App::CPAN2Pkg:
    file: lib/App/CPAN2Pkg.pm
    version: 1.1.0
  App::CPAN2Pkg::Curses:
    file: lib/App/CPAN2Pkg/Curses.pm
  App::CPAN2Pkg::Module:
    file: lib/App/CPAN2Pkg/Module.pm
  App::CPAN2Pkg::Worker:
    file: lib/App/CPAN2Pkg/Worker.pm
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
